services:
  - type: web
    name: neyrortwinbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: D_ID_API_KEY
        sync: false
      - key: ADMIN_ID
        sync: false
